// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exerciceEFAdresse.DbManager;

#nullable disable

namespace exerciceEFAdresse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("exerciceEFAdresse.Model.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComplementDeVoie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IntituleDeLaVoie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroDeVoie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Adresse");
                });
#pragma warning restore 612, 618
        }
    }
}
